#! /usr/bin/python3

import subprocess
import argparse

def get_brightness(): 
    # max brightness on my system is 852    
    max_brightness = 852
    file_name = "/sys/class/backlight/intel_backlight/brightness" 

    _brightness = 0 

    with open(file_name, 'r') as file:
        _brightness = file.read().replace('\n', '') 

    return int(_brightness) 

def inc_brightness(): 
    _brightness = get_brightness() 
    _brightness += int(852 * 0.1) 
    if _brightness >= 852: 
        _brightness = 852

    update_brightness(_brightness) 


def dec_brightness(): 
    _brightness = get_brightness() 
    if _brightness <= 0.2 * 852: 
        return; 
    _brightness -= int(852 * 0.1) 
    update_brightness(_brightness) 

def update_brightness(brightness): 
    _file = "/sys/class/backlight/intel_backlight/brightness" 
    _targ = open(_file, 'w') 
    _targ.write(str(brightness)) 
    _targ.close() 
    

def parse_args(): 
    parser = argparse.ArgumentParser(description="Update your display's brightness.")
    parser.add_argument("-i", action="store_true") 
    parser.add_argument("-d", action="store_true") 
    args = parser.parse_args() 

    if args.i: 
        inc_brightness() 
    elif args.d: 
        dec_brightness() 

if __name__ == '__main__': 
    parse_args() 
